[package]
name = "cg-playground"
version = "1.0.0"
authors = ["TN19N"]
edition = "2021"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
chrono = "0.4.26"
itertools = "0.11.0"
libc = "0.2.147"
rand = "0.8.5"
regex = "1.8.4"
time = "0.3.22"